-- BANK MANAGEMENT SYSTEM DATABASE PROJECT 
create database BMS_DB1;

use BMS_DB1;


-- Customer_Personal_INFO 

create table CUSTOMER_PERSONAL_INFO(
CUSTOMER_ID VARCHAR(5),
CUSTOMER_NAME VARCHAR(30),
DATE_OF_BIRTH DATE,
GUARDIAN_NAME VARCHAR(30),
ADDRESS VARCHAR(50),
CONTACT_NO BIGINT(10),
MAIL_ID VARCHAR(30),
GENDER CHAR(1),
MARITAL_STATUS VARCHAR(10),
IDENTIFICATION_DOC_TYPE VARCHAR(20),
ID_DOC_NO VARCHAR(10),
CITIZENSHIP VARCHAR(10),
CONSTRAINT CUST_PERS_INNFO_PK PRIMARY KEY(CUSTOMER_ID)
);

SHOW TABLES;

-- CUSTOMER_REFERENCE_INFO

CREATE TABLE CUSTOMER_REFERENCE_INFO(
CUSTOMER_ID VARCHAR(5),
REFERENCE_ACC_NAME VARCHAR(20),
REFERENCE_ACC_NO BIGINT(16),
REFERENCE_ACC_ADDRESS VARCHAR(50),
RELATION VARCHAR(25),
CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) 
REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);

SHOW TABLES;

-- BANK_INFO
CREATE TABLE BANK_INFO(
IFSC_CODE VARCHAR(15),
BANK_NAME VARCHAR(25),
BRANCH_NAME VARCHAR(25),
CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);

SHOW TABLES; 

-- ACCOUNT INFO 

CREATE TABLE ACCOUNT_INFO(
ACCOUNT_NO BIGINT(16),
CUSTOMER_ID VARCHAR(5),
ACCOUNT_TYPE VARCHAR(10),
REGISTRATION_DATE DATE,
ACTIVATION_DATE DATE,
IFSC_CODE VARCHAR(10),
INTEREST DECIMAL(7,2),
INITIAL_DEPOSITE BIGINT(10),
CONSTRAINT ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
CONSTRAINT ACC_INFO_PERS_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID),
CONSTRAINT ACC_INFO_FK FOREIGN KEY(IFSC_CODE) REFERENCES BANK_INFO(IFSC_CODE)
);

SHOW TABLES;

-- BANK INFO 
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('HDFC0012','HDFC','BHOPAL');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('SBIN0123','SBI','SHIVNI');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('ICITN0232','ICICI','BIKARE');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('ICIPG0242','ICICC','SIKAR');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('SBIN0113','SBI','LUKHNOW');

SELECT * FROM BANK_INFO;

-- CUSTOMER PERSONAL INFO 
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID ,CUSTOMER_NAME ,DATE_OF_BIRTH ,GUARDIAN_NAME ,ADDRESS ,CONTACT_NO ,MAIL_ID ,GENDER ,MARITAL_STATUS ,IDENTIFICATION_DOC_TYPE ,ID_DOC_NO ,CITIZENSHIP )
 VALUES ('C0001','RAM','1998-12-12','SOMDATT','BIKANER RAJASTHAN','9687543251','RAMC0001@GMAIL.COM','M','UNMARID','AADHAR','9686-2336','INDIAN');
 INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID ,CUSTOMER_NAME ,DATE_OF_BIRTH ,GUARDIAN_NAME ,ADDRESS ,CONTACT_NO ,MAIL_ID ,GENDER ,MARITAL_STATUS ,IDENTIFICATION_DOC_TYPE ,ID_DOC_NO ,CITIZENSHIP )
 VALUES ('C0002','SHYAM','1978-11-12','RAJARAM','SIKAR RAJASTHAN','9148357462','SHYAMC0002@GMAIL.COM','M','MARID','AADHAR','9825-3871','INDIAN');
 INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID ,CUSTOMER_NAME ,DATE_OF_BIRTH ,GUARDIAN_NAME ,ADDRESS ,CONTACT_NO ,MAIL_ID ,GENDER ,MARITAL_STATUS ,IDENTIFICATION_DOC_TYPE ,ID_DOC_NO ,CITIZENSHIP )
 VALUES ('C0003','SURESH','2000-12-02','DINESH','BHOPAL MADHYA PRADESH','8453157900','SURESHC0003@GMAIL.COM','M','UNMARID','VOTERID','9686-2336','INDIAN');
 INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID ,CUSTOMER_NAME ,DATE_OF_BIRTH ,GUARDIAN_NAME ,ADDRESS ,CONTACT_NO ,MAIL_ID ,GENDER ,MARITAL_STATUS ,IDENTIFICATION_DOC_TYPE ,ID_DOC_NO ,CITIZENSHIP )
 VALUES ('C0004','SHIVAM','2004-04-24','BALDEVSINGH','SHIVNI MADHYA PRADESH','9764851325','SHIVAMC00041@GMAIL.COM','M','MARID','AADHAR','1254-7824','INDIAN');
 INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID ,CUSTOMER_NAME ,DATE_OF_BIRTH ,GUARDIAN_NAME ,ADDRESS ,CONTACT_NO ,MAIL_ID ,GENDER ,MARITAL_STATUS ,IDENTIFICATION_DOC_TYPE ,ID_DOC_NO ,CITIZENSHIP )
 VALUES ('C0005','ROHANDAS','1998-01-10','MOHANDAS','LUKHNOW UTTAR PRADESH','9687543251','ROHANDASC0005@GMAIL.COM','M','UNMARID','AADHAR','0024-3971','INDIAN');
 
SELECT * FROM CUSTOMER_PERSONAL_INFO;

--  CUSTOMER REFERENCE INFO 

INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID ,REFERENCE_ACC_NAME ,REFERENCE_ACC_NO ,REFERENCE_ACC_ADDRESS ,RELATION )
VALUES('C0001','RAM','827210007598','BIKANER RAJASTHAN','SON');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID ,REFERENCE_ACC_NAME ,REFERENCE_ACC_NO ,REFERENCE_ACC_ADDRESS ,RELATION )
VALUES('C0002','SHYAM','827210001579','SIKAR RAJASTHAN','SON');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID ,REFERENCE_ACC_NAME ,REFERENCE_ACC_NO ,REFERENCE_ACC_ADDRESS ,RELATION )
VALUES('C0003','SURESH','49863951384','BHOPAL MADHYA PRADESH','SON');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID ,REFERENCE_ACC_NAME ,REFERENCE_ACC_NO ,REFERENCE_ACC_ADDRESS ,RELATION )
VALUES('C0004','SHIVAM','82584500057','SHIVNI MADHYA PRADESH','SON');
INSERT INTO CUSTOMER_REFERENCE_INFO(CUSTOMER_ID ,REFERENCE_ACC_NAME ,REFERENCE_ACC_NO ,REFERENCE_ACC_ADDRESS ,RELATION )
VALUES('C0005','ROHANDAS','48980001111','LUKHNOW UTTAR PRADESH','NEPHEW');

SELECT * FROM CUSTOMER_REFERENCE_INFO;
 